org.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.tooling.parallel=true

kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true

beamSdk.androidAbis=armeabi-v7a,arm64-v8a
beamSdk.ndkVersion=27.0.12077973
beamSdk.coreCommit=9c4366aae08e7fbde7bc8d65f828a0deace68bfc
beamSdk.coreTag=beam-7.5.14493
